### ISSUE TITLE
How to use Perspective Camera?

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#12]
I tried to display [MetalRoughSpheres.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MetalRoughSpheres) in RedCube.js.
However, it seems that the sphere behind is not displayed.
It is probably because RedCube.js uses `Orthographic Camera` instead of `Perspective Camera`.

[RedCube.js + MetalRoughSpheres.gltf result:](http://jsdo.it/cx20/qCS6)
![image](https://user-images.githubusercontent.com/1833979/51064855-32106300-1645-11e9-8d9d-4a942b4857af.png)

[Three.js + MetalRoughSpheres.gltf result:](http://jsdo.it/cx20/SMjx)
![image](https://user-images.githubusercontent.com/1833979/51064902-6421c500-1645-11e9-873e-63c8fad30129.png)

Can I use Perspective Camera with RedCube.js?

**Comment by Reon90** [comment]
Was fixed in 2.1.0

**Comment by cx20** [comment]
Thanks! I have confirmed that the latest version of RedCube.js uses Perspective Camera.

[RedCube.js 2.1.0 + MetalRoughSperes.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/8e2a1b88cfa0633dcf63083a6b3ac05266da1fd6/examples/redcube/index.html?category=tutorialModels&model=MetalRoughSpheres&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/80295031-fbaf1680-87a9-11ea-9fff-d5db077544f1.png)
