### ISSUE TITLE
Models in the KHR_mesh_quantization extension do not display correctly

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#14]
I have tried some models of the `KHR_mesh_quantization` extension with the latest version of RedCube.js.
However, it doesn't seem to display as expected.

[RedCube.js v2.2.0 + AnimatedMorphCube/glTF result:](https://rawcdn.githack.com/cx20/gltf-test/46df65d91c2032e1057980d517a17a69b3f5723a/examples/redcube/index.html?category=tutorialModels&model=AnimatedMorphCube&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/80855700-551db680-8c7e-11ea-9900-1d2b333ab200.png)

[RedCube.js v2.2.0 + AnimatedMorphCube/glTF-Quantized result:](https://rawcdn.githack.com/cx20/gltf-test/46df65d91c2032e1057980d517a17a69b3f5723a/examples/redcube/index.html?category=tutorialModels&model=AnimatedMorphCube&scale=1&type=glTF-Quantized)
![image](https://user-images.githubusercontent.com/1833979/80855736-96ae6180-8c7e-11ea-9ceb-e3975b312d2a.png)

**Comment by Reon90** [comment]
@cx20 was fixed in 2.3.0

**Comment by cx20** [comment]
I confirmed that the display of `AnimatedMorphCube.gltf` has been resolved in the latest version of the library.

It looks pretty good, but it seems that `Duck`'s model has a strange display when the `KHR_mesh_quantization` extension is used. Can you investigate?

[RedCube v2.3.0 + Duck/glTF result:](https://rawcdn.githack.com/cx20/gltf-test/bbe954fbb47ee78ec5f0233e2dd340b5016a973e/examples/redcube/index.html?category=sampleModels&model=Duck&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/80870869-115d9800-8ce4-11ea-8ec0-f90a8a664ea3.png)

[RedCube v2.3.0 + Duck/glTF-Quantized result:](https://rawcdn.githack.com/cx20/gltf-test/bbe954fbb47ee78ec5f0233e2dd340b5016a973e/examples/redcube/index.html?category=tutorialModels&model=Duck&scale=1&type=glTF-Quantized)
![image](https://user-images.githubusercontent.com/1833979/80870892-36eaa180-8ce4-11ea-80c8-376584b67410.png)

**Comment by Reon90** [comment]
@cx20 was fixed in 2.5.0.
Also KHR_materials_transmission, KHR_materials_sheen and etc were implemented.

**Comment by cx20** [comment]
@Reon90 I'm currently trying `RedCube.js 2.5.0` locally.
However, it seems that a strange pattern is displayed. Is it a matter of usage?

![image](https://user-images.githubusercontent.com/1833979/105619166-55c13300-5e33-11eb-97a5-e19ad660e2d1.png)
![image](https://user-images.githubusercontent.com/1833979/105619182-7db09680-5e33-11eb-9089-999974f8b4f5.png)

**Comment by cx20** [comment]
Below is the display result of `Duck.gltf` in the online demo.
https://reon90.github.io/redcube/
![image](https://user-images.githubusercontent.com/1833979/105619320-c9b00b00-5e34-11eb-9260-42dfd4d14034.png)

**Comment by Reon90** [comment]
@cx20 thank you, there was some issue with irradiance map.
Please try 2.5.1.

**Comment by cx20** [comment]
@Reon90 Thank you for the correction.
I have confirmed that the latest version of RedCube.js displays the model correctly.

[RedCube v2.5.1 + Duck/glTF-Quantized result:](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=Duck&scale=1&type=glTF-Quantized)
![image](https://user-images.githubusercontent.com/1833979/105633309-2f36e280-5e9b-11eb-8872-e2fcc6de2f85.png)
