### ISSUE TITLE
Failed to load Duck model in glTF-Embedded format

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#17]
I tried to use [gltf-test](https://github.com/cx20/gltf-test) to display the `Duck` model in `glTF-Embedded` format.
However, it seems to fail to load the resource and cannot be displayed.

[RedCube.js + Duck/glTF-Embedded result:](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=sampleModels&model=Duck&scale=1&type=glTF-Embedded)

![image](https://user-images.githubusercontent.com/1833979/105670333-3950f380-5f24-11eb-9f18-b911111a6625.png)

**Comment by Reon90** [comment]
@cx20 fixed in 2.5.3

**Comment by cx20** [comment]
Thanks. I have confirmed that the error has been resolved in the latest version.
