### ISSUE TITLE
The display result of KHR_texture_basisu extension is different from what is expected.

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#18]
I tried to display the model of the `KHR_texture_basisu` extension in the latest version of `RedCube.js`.
However, I expected the results to be the same, but the results seem to be displayed differently.

|[glTF](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=FlightHelmet&scale=3&type=glTF)|[BasisU](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=FlightHelmet&scale=3&type=glTF-BasisU)|
|:----:|:----:|
|[![image](https://user-images.githubusercontent.com/1833979/105670736-dad84500-5f24-11eb-97d9-8391d77b0077.png)](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=FlightHelmet&scale=3&type=glTF)|[![image](https://user-images.githubusercontent.com/1833979/105670750-e0358f80-5f24-11eb-8532-1d0c4d094119.png)](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=FlightHelmet&scale=3&type=glTF-BasisU)|

**Comment by Reon90** [comment]
@cx20 fixed in 2.5.3

**Comment by cx20** [comment]
Thanks! I have confirmed that the latest version solves the problem.

|[glTF](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=FlightHelmet&scale=3&type=glTF)|[BasisU](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=FlightHelmet&scale=3&type=glTF-BasisU)|
|:----:|:----:|
|[![image](https://user-images.githubusercontent.com/1833979/106015001-660e3200-6101-11eb-80f1-480731a6067c.png)](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=FlightHelmet&scale=3&type=glTF)|[![image](https://user-images.githubusercontent.com/1833979/106015083-76261180-6101-11eb-815b-e1027e63bb1a.png)](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=FlightHelmet&scale=3&type=glTF-BasisU)|
