### ISSUE TITLE
Cesium Man's skinning animation is incorrect

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#19]
I tried to view [CesiumMan](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMan) with RedCube.js v.2.5.3.
However, the mesh of the model seems to be distorted for a moment.

[RedCube.js + CesiumMan.gltf result:](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=sampleModels&model=CesiumMan&scale=1&type=glTF)
![RedCube_CesiumMan_problem_002](https://user-images.githubusercontent.com/1833979/106017291-a66eaf80-6103-11eb-8ffb-2c3533be5a46.gif)

**Comment by Reon90** [comment]
@cx20 fixed in 2.5.4

**Comment by cx20** [comment]
Thank you for the quick fix. I have confirmed that the latest version solves the problem.
