### ISSUE TITLE
Unnatural shadows in Sheen extension model

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#20]
I have tested several Sheen extension models.
`Babylon.js` looks good, but `RedCube.js` seems to show unnatural shadows.

|Model|Babylon.js|RedCube.js|
|:------:|:------:|:------:|
|SheenChair.gltf (small)|![image](https://user-images.githubusercontent.com/1833979/106206475-7c041b80-6203-11eb-84ab-edbef3845f78.png)|![image](https://user-images.githubusercontent.com/1833979/106206492-82929300-6203-11eb-855e-a05c69f5c166.png)|
|SheenChair.gltf (large)|![image](https://user-images.githubusercontent.com/1833979/106206690-d8673b00-6203-11eb-827a-46761b737314.png)|![image](https://user-images.githubusercontent.com/1833979/106206697-ddc48580-6203-11eb-9c5f-215e1502bfab.png)|
|ToyCar.gltf (large)|![image](https://user-images.githubusercontent.com/1833979/106207163-a4404a00-6204-11eb-8d28-6b3d0b6f8766.png)|![image](https://user-images.githubusercontent.com/1833979/106207181-ab675800-6204-11eb-9e2c-e48680298c61.png)|

**Comment by Reon90** [comment]
@cx20 fixed in 2.5.5

**Comment by cx20** [comment]
@Reon90 Thanks! I tried the latest version. I think the unnaturalness has been improved.

|Model|RedCube.js(v2.5.4)|RedCube.js(v2.5.6)
|:------:|:------:|:------:|
|SheenChair.gltf (small)|![image](https://user-images.githubusercontent.com/1833979/106206492-82929300-6203-11eb-855e-a05c69f5c166.png)|![image](https://user-images.githubusercontent.com/1833979/108065722-c27dc500-70a1-11eb-9dec-a47e362ec37c.png)|
|SheenChair.gltf (large)|![image](https://user-images.githubusercontent.com/1833979/106206697-ddc48580-6203-11eb-9c5f-215e1502bfab.png)|![image](https://user-images.githubusercontent.com/1833979/108065743-cad60000-70a1-11eb-9d9d-f978c526f682.png)|
|ToyCar.gltf (large)|![image](https://user-images.githubusercontent.com/1833979/106207181-ab675800-6204-11eb-9e2c-e48680298c61.png)|![image](https://user-images.githubusercontent.com/1833979/108065771-d32e3b00-70a1-11eb-99b1-e2a842464b51.png)|

I think the ToyCar cloth is a little dark, but I think it's another problem, so I'm going to close this issue.
