### ISSUE TITLE
RiggedSimple's shade becomes unnatural when the light is in PBR mode.

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#22]
I have tried to display the RiggedSimple model on the RedCube.js [online demo](https://reon90.github.io/redcube/) page.
However, the shade seem to be displayed unnaturally when the light mode is set to PBR.

https://reon90.github.io/redcube/

|Light mode|image|
|:----:|:-----:|
|pbr|![image](https://user-images.githubusercontent.com/1833979/106332401-162e9700-62ca-11eb-9a36-6005fdb89e6b.png)|
|phong|![image](https://user-images.githubusercontent.com/1833979/106332413-1f1f6880-62ca-11eb-9cda-e9f9e0a9906f.png)|

**Comment by Reon90** [comment]
@cx20 please turn off the light checkbox. It's not related to gltf. I will remove it from demo page.

**Comment by cx20** [comment]
Hmm, when the light is turned off, the result is as follows. Is it the expected operation?
The function of light seems to be alive just by resetting the position of the slider of light.

|mode|image|
|:----:|:-----:|
|pbr(light off)|![image](https://user-images.githubusercontent.com/1833979/106339585-6281d300-62da-11eb-84cc-ffd21011d675.png)
|phong(light off)|![image](https://user-images.githubusercontent.com/1833979/106339741-d8863a00-62da-11eb-94a2-2fa5afdbaa5d.png)|

**Comment by Reon90** [comment]
@cx20 fixed in 2.5.5

**Comment by cx20** [comment]
@Reon90 Thsnks! I think the problem has been resolved.

|mode|image|
|:----:|:-----:|
|pbr|![image](https://user-images.githubusercontent.com/1833979/107999915-11891300-702c-11eb-90e8-d43e7fed2cbe.png)|
|phong|![image](https://user-images.githubusercontent.com/1833979/107999934-1bab1180-702c-11eb-820c-c1b3ddf4b09c.png)|
