### ISSUE TITLE
Switching ToyCar's built-in camera does not work 

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#23]
I have tried switching ToyCar's built-in camera on the [demo page](https://reon90.github.io/redcube/). However, selecting the camera does not seem to switch correctly.
I tried switching the camera from "10" to "3" but the screen didn't change.

https://reon90.github.io/redcube/
![image](https://user-images.githubusercontent.com/1833979/108066585-df66c800-70a2-11eb-9344-c374d1dc1b86.png)

**Comment by Reon90** [comment]
@cx20 fixed demo page

**Comment by cx20** [comment]
@Reon90  Thank you for your quick fix. I have confirmed that I can now switch cameras on the demo page.
![image](https://user-images.githubusercontent.com/1833979/108129017-eb797680-70f0-11eb-852d-98186f9f44a7.png)
