### ISSUE TITLE
TransmissionTest.gltf is dark when the light is only IBL

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#24]
I tried to display [TransmissionTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TransmissionTest) in RedCube.js.
However, when the light is only `IBL`, it seems to appear darker than expected.

|IBL|lights|[RedCube.js + TransmissionTest.gltf result](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=TransmissionTest&scale=3&type=glTF)|
|:----:|:----:|:-----:|
|on |off|![image](https://user-images.githubusercontent.com/1833979/108072309-12608a00-70aa-11eb-9288-e4b79b7698e5.png)|
|on|on|![image](https://user-images.githubusercontent.com/1833979/108072395-2f955880-70aa-11eb-91ef-c9d0edd54143.png)|

Is this the expected result?

**Comment by Reon90** [comment]
@cx20 fixed in 2.5.7

**Comment by cx20** [comment]
@Reon90 Thank you for the improvement. I think the darkened part has improved. However, it seems to be a little different from the expected result. There seems to be a black band where it should be transparent.

[Expected result:](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TransmissionTest)
![image](https://user-images.githubusercontent.com/1833979/108135202-0e108d00-70fb-11eb-8740-9f2347fcfa05.png)

[Current result:](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=TransmissionTest&scale=3&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/108135088-d3a6f000-70fa-11eb-8e09-cf8dbcdacf5f.png)

**Comment by Reon90** [comment]
@cx20 fixed in 2.5.8

**Comment by cx20** [comment]
@Reon90 Thanks! I think it has been improved in the latest version.

![image](https://user-images.githubusercontent.com/1833979/108192181-4d6cc700-7157-11eb-88a3-b6e5d4bf4f6d.png)
