### ISSUE TITLE
NormalTangentTest.gltf is different from expected result

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#25]
I tried to display [NormalTangentTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentTest) in RedCube.js. However, it seems to be different from the expected result.

[RedCube.js + NormalTangentTest.gltf result:](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=NormalTangentTest&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/108084782-f6fc7b80-70b7-11eb-9543-23fae9440128.png)

Expected result:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentTest
![image](https://user-images.githubusercontent.com/1833979/108084844-07145b00-70b8-11eb-85e3-e3c45871ace9.png)

**Comment by Reon90** [comment]
@cx20 fixed in 2.5.7

**Comment by cx20** [comment]
@Reon90 Thanks! I have confirmed that this has been fixed.
![image](https://user-images.githubusercontent.com/1833979/108134437-92faa700-70f9-11eb-940d-520570be8e3b.png)

**Comment by cx20** [comment]
@Reon90 It may be another problem, but can you check the [following models](https://ft-lab.github.io/gltf.html) as well?
https://ft-lab.github.io/gltf/normal_map/normal_test_02.glb

Expected result:
![image](https://user-images.githubusercontent.com/1833979/102695337-fa1aed00-4269-11eb-846c-2cd6604229e4.png)

Current result:
![image](https://user-images.githubusercontent.com/1833979/108134837-3fd52400-70fa-11eb-8c9a-0c3a765358ef.png)
