### ISSUE TITLE
The scale of the teacup normal map is not correctly reflected

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#26]
I tried the model of a teacup in the following repository with RedCube.
However, I think that RedCube does not correctly reflect the normal scale of the teacup.

https://ft-lab.github.io/gltf.html

https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_20.glb
![image](https://user-images.githubusercontent.com/1833979/91868955-4688ef80-ecb0-11ea-9be1-926551a66a8a.png)

Click the image below to go to the sample URL.

|library|normal 0.5|normal 1.0|normal 2.0|
|:-----:|:-----:|:-----:|:-----:|
|Three.js|[![image](https://user-images.githubusercontent.com/1833979/99108407-9b3ed400-262a-11eb-9e4d-e707bcdf7b00.png)](https://cx20.github.io/gltf-test/examples/threejs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_05.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/99108476-bb6e9300-262a-11eb-80bb-56f0ce3fd1e1.png)](https://cx20.github.io/gltf-test/examples/threejs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_10.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/99108489-c32e3780-262a-11eb-8236-7ffc57290119.png)](https://cx20.github.io/gltf-test/examples/threejs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_20.glb&scale=15)|
|Babylon.js|[![image](https://user-images.githubusercontent.com/1833979/99108521-d0e3bd00-262a-11eb-8461-0d38b1b5e488.png)](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_05.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/99108536-d7723480-262a-11eb-94ae-9196db2f5ba3.png)](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_10.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/99108549-dccf7f00-262a-11eb-8b31-cb6a6e5a1fe0.png)](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_20.glb&scale=15)|
|RedCube|[![image](https://user-images.githubusercontent.com/1833979/108136071-a8250500-70fc-11eb-9158-ecdbe8220eb5.png)](https://cx20.github.io/gltf-test/examples/redcube/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_05.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/108136086-afe4a980-70fc-11eb-840d-ca435bc3985f.png)](https://cx20.github.io/gltf-test/examples/redcube/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_10.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/108136103-b8d57b00-70fc-11eb-985b-f9acd69d58e9.png)](https://cx20.github.io/gltf-test/examples/redcube/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_20.glb&scale=15)|

**Comment by Reon90** [comment]
@cx20 fixed in 2.5.8

**Comment by cx20** [comment]
@Reon90 Thanks for the improvement. However, I don't think `normal 0.5` is being applied. Could you please check?

|library|normal 0.5|normal 1.0|normal 2.0|
|:-----:|:-----:|:-----:|:-----:|
|RedCube (before)|![image](https://user-images.githubusercontent.com/1833979/108136071-a8250500-70fc-11eb-9158-ecdbe8220eb5.png)|![image](https://user-images.githubusercontent.com/1833979/108136086-afe4a980-70fc-11eb-840d-ca435bc3985f.png)|![image](https://user-images.githubusercontent.com/1833979/108136103-b8d57b00-70fc-11eb-985b-f9acd69d58e9.png)|
|RedCube (after)|![image](https://user-images.githubusercontent.com/1833979/108194179-a6d5f580-7159-11eb-87db-40d3a74b2294.png)|![image](https://user-images.githubusercontent.com/1833979/108194210-af2e3080-7159-11eb-9798-e2456ee505cc.png)|![image](https://user-images.githubusercontent.com/1833979/108194246-ba815c00-7159-11eb-9b70-53b4d909e37d.png)|

**Comment by cx20** [comment]
Below are other verification test models.
https://ft-lab.github.io/gltf/pbr_material/gltfTest_PBRMaterial.glb

Expected result:
![image](https://user-images.githubusercontent.com/1833979/108198916-96287e00-715f-11eb-8a5b-5489ccfa05b5.png)
The scale `0.2`, `0.5`, `1.0` of the normal map from the left is specified.

Current result:
![image](https://user-images.githubusercontent.com/1833979/108198993-b6583d00-715f-11eb-9cc8-4ce7be91b8e0.png)

**Comment by Reon90** [comment]
@cx20 fixed in 2.5.9

**Comment by cx20** [comment]
@Reon90 I am always grateful for your help. I think it has been improved in the latest version.

|library|normal 0.5|normal 1.0|normal 2.0|
|:-----:|:-----:|:-----:|:-----:|
|RedCube v2.5.9|![image](https://user-images.githubusercontent.com/1833979/108283212-46c96880-71c6-11eb-8ba5-21abeca33f4a.png)|![image](https://user-images.githubusercontent.com/1833979/108283234-4df07680-71c6-11eb-92e3-2427b58edaa3.png)|![image](https://user-images.githubusercontent.com/1833979/108283261-52b52a80-71c6-11eb-9c3b-5f3c375507d9.png)|

Current result:
![image](https://user-images.githubusercontent.com/1833979/108283491-ae7fb380-71c6-11eb-91df-d64935ce68b1.png)
