### ISSUE TITLE
Tangent Space test model is not displayed correctly

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#27]
I tried to view the test model below. However, it seems to be different from what was expected.
https://ft-lab.github.io/gltf/normal_map/normal_test_02.glb

Expected result:
![image](https://user-images.githubusercontent.com/1833979/102695337-fa1aed00-4269-11eb-846c-2cd6604229e4.png)

Current result:
![image](https://user-images.githubusercontent.com/1833979/108134837-3fd52400-70fa-11eb-8c9a-0c3a765358ef.png)

**Comment by Reon90** [comment]
@cx20 fixed in 2.5.10

**Comment by cx20** [comment]
@Reon90 Thanks! I think this has been resolved in the latest version.
![image](https://user-images.githubusercontent.com/1833979/108499980-78d7e900-72f2-11eb-82c0-3ee6d9ddcdab.png)
