### ISSUE TITLE
When using IBL, the display result of SpecGlossVsMetalRough.gltf is different from expected

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#28]
I tried to view [SpecGlossVsMetalRough.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SpecGlossVsMetalRough) in RedCube.js. 
However, when using only `IBL` for the light, the display result seems to be different from what I expected.

Expected result:
![image](https://user-images.githubusercontent.com/1833979/108501435-a3c33c80-72f4-11eb-84fc-147efc6a2c89.png)

Current result:
|IBL|Lights|[RedCube + SpecGlossVsMetalRough.gltf result](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=SpecGlossVsMetalRough&scale=10&type=glTF)|
|:---:|:---:|:---:|
|on|off|![image](https://user-images.githubusercontent.com/1833979/108501302-737b9e00-72f4-11eb-82e0-42b250a7359e.png)|
|on|on|![image](https://user-images.githubusercontent.com/1833979/108500889-c9037b00-72f3-11eb-952e-aa2f789b2b48.png)|

**Comment by Reon90** [comment]
@cx20 fixed in 2.5.11

**Comment by cx20** [comment]
@Reon90 Thanks! I have confirmed that the problem has been improved in the latest version.

![image](https://user-images.githubusercontent.com/1833979/108577111-3a2e4700-7363-11eb-843a-71b9c6546b13.png)
