### ISSUE TITLE
How to use RedCube.js?

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#3]
I am currently creating a sample that displays glTF files in RedCube.js.
https://github.com/cx20/gltf-test/tree/master/examples/redcube

However, I can not solve the phenomenon that half of the screen becomes gray.
[RedCube.js + FlightHelmet.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/c8158833e912fc3ec79cdea62584c3917f97559c/examples/redcube/index.html?category=tutorialModels&model=FlightHelmet&scale=5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/50532542-147bcd80-0b5e-11e9-9f14-afdd5e493f50.png)

I think that usage is probably wrong. It will be helpful to get advice.
```javascript
const renderer = new redcube.RedCube(
    url,
    canvas,
    ['light'],
    '../../../../textures/hdr/pisa'
);
```

**Comment by Reon90** [comment]
@cx20 you should replace ['light'] to []

**Comment by cx20** [comment]
@Reon90 Thanks! I solved the problem.
![image](https://user-images.githubusercontent.com/1833979/50536404-6a209c00-0b97-11e9-8400-b13fa036bba0.png)
