### ISSUE TITLE
ToyCarSpecular.gltf is different from expected result

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#32]
I tried [ToyCarSpecular.gltf](https://github.com/proog128/glTF-Sample-Models/tree/KHR_materials_specular/2.0/ToyCar), a draft model of Khronos. (The model has been renamed in the gltf-test repository to distinguish it from [ToyCar.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/ToyCar).)
This model demonstrates the usage of `KHR_materials_specular`, `KHR_materials_ior`, `KHR_materials_transmission` and `KHR_materials_clearcoat`.
Please note that this model is different from [this sample](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/ToyCar).

I noticed about two problems when compared with Babylon.js.

- When only IBL is on, the flame emblem and car number are specularly reflected.
- The part of the cloth looks like a metallic luster

|IBL|Lights|[Babylon.js + ToyCarSpecular.gltf result:](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=ToyCarSpecular&scale=5&type=glTF)|[RedCube.js + ToyCarSpecular.gltf result:](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=ToyCarSpecular&scale=5&type=glTF)|
|:---:|:---:|:---:|:---:|
|off|off|![image](https://user-images.githubusercontent.com/1833979/108579650-4a4a2480-736b-11eb-862b-4b491de31496.png)|![image](https://user-images.githubusercontent.com/1833979/108579681-6e0d6a80-736b-11eb-87db-21cae57a2f3a.png)|
|off|on|![image](https://user-images.githubusercontent.com/1833979/108579663-5209c900-736b-11eb-8d65-202d4000c654.png)|![image](https://user-images.githubusercontent.com/1833979/108579687-74034b80-736b-11eb-8076-5c21514315d8.png)|
|on|off|![image](https://user-images.githubusercontent.com/1833979/108579669-5930d700-736b-11eb-9f56-aa7331c57fdb.png)|![image](https://user-images.githubusercontent.com/1833979/108579695-79609600-736b-11eb-8b65-528bf36a7a0d.png)|
|on|on|![image](https://user-images.githubusercontent.com/1833979/108579676-651c9900-736b-11eb-909a-2724867e9fe9.png)|![image](https://user-images.githubusercontent.com/1833979/108579702-7ebde080-736b-11eb-8e0f-5a5d00d570f5.png)|

**Comment by Reon90** [comment]
@cx20 do you have source of model?

**Comment by cx20** [comment]
> do you have source of model, because I'm not sure about fabric material

The glTF file is shown below, but you will have to ask the creator if there is an original source.
[ToyCarSpecular.zip](https://github.com/Reon90/redcube/files/6022201/ToyCarSpecular.zip)

> The part of the cloth looks like a metallic luster

The areas that I see as metallic luster are as follows.
In Babylon.js, Fabric reflects the Base Color texture, but in Red Cube it appears to have a metallic luster.

|Library|ToyCarSpecular.gltf result|
|:----:|:----:|
|Babylon.js|![image](https://user-images.githubusercontent.com/1833979/108714111-78428b00-755c-11eb-90b2-21f7e585d948.png)|
|RedCube.js|![image](https://user-images.githubusercontent.com/1833979/108714142-855f7a00-755c-11eb-9437-88a4c5442b79.png)|

**Comment by cx20** [comment]
> When only IBL is on, the flame emblem and car number are specularly reflected. - fixed in 2.5.12

I confirmed this. Thank you for your support.

**Comment by Reon90** [comment]
@cx20 I’m trying to told you that Babylonjs is not source of true. To verify rendering we need some ground true renderer, e.g. Blender etc.

**Comment by cx20** [comment]
Below is the result of path-traced. Perhaps this is the expected result.
https://github.com/KhronosGroup/glTF-Sample-Models/pull/268#issuecomment-669034471
![image](https://user-images.githubusercontent.com/2821679/89384954-34428280-d6ff-11ea-9eba-b57cbe755618.png)

[Current result:](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=ToyCarSpecular&scale=10&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/108780149-60debe80-75ab-11eb-994f-d0623f21bbd4.png)

**Comment by cx20** [comment]
@emackey Any advice on how to test `KHR_materials_specular`?

**Comment by emackey** [comment]
We're still working to get a better test model for specular.  The toy car is the only one available at this point, but for me at least, it's not intuitive why the car comes out that color.  It would be better for us to have a model that's more explicit, but we don't have one yet.

The closest thing to ground truth currently is a prototype path tracer from Dassault.  But there was a change to the specular parameters just a couple weeks ago, and I don't know if this path tracer was updated to support that yet.  This should all get straightened out before we send specular over for ratification.

Live: https://dassaultsystemes-technology.github.io/dspbr-pt/

Source: https://github.com/dassaultsystemes-technology/dspbr-pt/

**Comment by cx20** [comment]
@emackey Thanks for the advice. I have tried Dassault's path tracer. 
However, unfortunately, I could not determine if that was the correct result.

[Dassault's path tracer](https://dassaultsystemes-technology.github.io/dspbr-pt/) + [ToyCarSpecular.gltf](https://github.com/proog128/glTF-Sample-Models/tree/KHR_materials_specular/2.0/ToyCar)(using the `KHR_materials_specular` extension) result:
![image](https://user-images.githubusercontent.com/1833979/109170323-040a2080-77c4-11eb-994c-46048a1ddeb8.png)

Since this extension is not yet finished, we may have to work on another issue first.

**Comment by Reon90** [comment]
@cx20 fixed in 2.5.13

**Comment by cx20** [comment]
@Reon90  Thanks! It looks good.

||result|
|:----:|:----:|
|before|![image](https://user-images.githubusercontent.com/1833979/109370917-b8e82e80-78e5-11eb-80ae-e41b3c1ede5f.png)|
|after|![image](https://user-images.githubusercontent.com/1833979/109370944-dc12de00-78e5-11eb-84fb-85953348197e.png)|

**Comment by cx20** [comment]
@Reon90 The cloth seems dark when I view `ToyCarSpecular.gltf` on the latest version of RedCube. Can you confirm it?

||result|
|:----:|:----:|
|RedCube 2.5.13|[![image](https://user-images.githubusercontent.com/1833979/109370944-dc12de00-78e5-11eb-84fb-85953348197e.png)](https://rawcdn.githack.com/cx20/gltf-test/c7aeb61dc68371fb55d5fbab6675c1983e8ca8d8/examples/redcube/index.html?category=tutorialModels&model=ToyCarSpecular&scale=10&type=glTF)|
|RedCube 3.0.2|[![image](https://user-images.githubusercontent.com/1833979/120343646-dc32d780-c333-11eb-96a4-8a41508272b9.png)](https://rawcdn.githack.com/cx20/gltf-test/89c33e1c43c0f34d70f129d87a20c2a6f16aa6a0/examples/redcube/index.html?category=tutorialModels&model=ToyCarSpecular&scale=10&type=glTF)|

**Comment by Reon90** [comment]
fixed in 3.2.0

**Comment by Reon90** [comment]
@cx20 could you check?

**Comment by cx20** [comment]
I have confirmed this model again with RedCube v3.3.0. I think the cloth is brighter than before.

[![image](https://user-images.githubusercontent.com/1833979/163674730-291f2bb4-e79d-485e-9c84-251c7ff8c364.png)](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=ToyCarSpecular&scale=10&type=glTF)

@emackey Is it possible to determine if the brightness of this cloth is correct? Personally, I don't feel so uncomfortable, so I feel that the test has passed.

**Comment by emackey** [comment]
@cx20 Let's disregard the cloth on this particular version of the ToyCar model.  Fabric and sheen effects have other tests that have already been merged into the official repo.  This version of ToyCar is due to be replaced eventually.  Thanks.

**Comment by cx20** [comment]
@emackey Thanks for the advice.

@Reon90 I would like to ignore the effects of Fabric and sheen as advised by emackey. I marked the test as passing in gltf-test.
