### ISSUE TITLE
When using only IBL, ToyCar display result is different from expected

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#34]
I used RedCube to display [ToyCar.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/ToyCar), which is a representative model of [PBR Next Phase1](https://www.khronos.org/news/press/khronos-releases-wave-of-new-gltf-pbr-3d-material-capabilities).
However, when using only `IBL`, the results of the [KHR_materials_sheen](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_sheen) extension seem to be different than expected.

|IBL|Lights|[Babylon.js + ToyCar.gltf result:](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=ToyCar&scale=100&type=glTF)|[RedCube.js + ToyCar.gltf result:](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=ToyCar&scale=100&type=glTF)|
|:---:|:---:|:---:|:---:|
|off|off|![image](https://user-images.githubusercontent.com/1833979/109178152-e8a31380-77cb-11eb-807b-8c36050785f1.png)|![image](https://user-images.githubusercontent.com/1833979/109178128-e2149c00-77cb-11eb-87a4-5bcc723962b3.png)|
|off|on|![image](https://user-images.githubusercontent.com/1833979/109178268-053f4b80-77cc-11eb-8785-62642a49da32.png)|![image](https://user-images.githubusercontent.com/1833979/109178245-fe183d80-77cb-11eb-8de0-1fba7f758b99.png)|
|on|off |![image](https://user-images.githubusercontent.com/1833979/109178197-f3f63f00-77cb-11eb-9d0c-e085b8a7a050.png)|![image](https://user-images.githubusercontent.com/1833979/109178175-ee98f480-77cb-11eb-8bf6-08174ca20619.png)|
|on |on |![image](https://user-images.githubusercontent.com/1833979/109178321-14be9480-77cc-11eb-8fa1-d65c6a02eca2.png)|![image](https://user-images.githubusercontent.com/1833979/109178293-0d978680-77cc-11eb-8a3f-c1311abe0058.png)|

**Comment by Reon90** [comment]
@cx20 fixed in 2.5.13

**Comment by cx20** [comment]
@Reon90 Thank you for the improvement. It looks good.

||result|
|:----:|:----:|
|before|![image](https://user-images.githubusercontent.com/1833979/109370841-5bec7880-78e5-11eb-9b6a-594011991d92.png)|
|after|![image](https://user-images.githubusercontent.com/1833979/109370849-627af000-78e5-11eb-8b77-39e98a155a98.png)|
