### ISSUE TITLE
SheenCloth.gltf shows a strange pattern

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#35]
I tried to display [SheenCloth.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SheenCloth) in RedCube. However, it seems to display a strange pattern.

|library|result|
|:-----:|:-----:|
|Expected result|![image](https://user-images.githubusercontent.com/1833979/109371094-9571b380-78e6-11eb-9f4b-14023280025e.png)|
|RedCube v2.5.12|![image](https://user-images.githubusercontent.com/1833979/109371029-4d529100-78e6-11eb-9e73-f60a1d38ce94.png)
|RedCube v2.5.13|![image](https://user-images.githubusercontent.com/1833979/109370979-09f82280-78e6-11eb-9748-b7761015ff85.png)|

**Comment by Reon90** [comment]
@cx20 there was a bug with texture transforms, fixed in 2.5.14.

**Comment by cx20** [comment]
@Reon90 Thanks! I think the latest version has improved the problem.

![image](https://user-images.githubusercontent.com/1833979/109386759-46f10300-7940-11eb-8593-aae0c4ff238e.png)
