### ISSUE TITLE
When I select variants in SheenChair.gltf, a strange pattern appears

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#36]
I tried to display [SheenChair.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SheenChair) in RedCube.
However, in some cases, when I re-select the Variants, a strange pattern appears.

Excepted result:
![image](https://user-images.githubusercontent.com/1833979/109387104-a819d600-7942-11eb-8d66-b58f07a4fb4e.png)

Current result:
![image](https://user-images.githubusercontent.com/1833979/109386984-d519b900-7941-11eb-96a5-2cfdf2913d4e.png)

**Comment by Reon90** [comment]
@cx20 fixed in 2.5.15

**Comment by cx20** [comment]
@Reon90 Thanks! I think this has been improved in the latest version.
![image](https://user-images.githubusercontent.com/1833979/109392198-2afc5a00-795e-11eb-8c38-246744bfc739.png)
