### ISSUE TITLE
RecursiveSkeletons.gltf cannot be displayed

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#39]
I tried [RecursiveSkeletons.gltf](https://github.com/vpenades/glTF-Sample-Models/tree/master/2.0/RecursiveSkeletons), a test model proposed by Khronos.
However, it seems that nothing is displayed on RedCube.

Expected result:
![image](https://user-images.githubusercontent.com/1833979/109888488-f1618100-7cc6-11eb-849b-3e3daff0aaa3.png)

[Current result](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=RecursiveSkeletons&scale=0.01&type=glTF):
Nothing is displayed

**Edit 2021.05.10**
Since the link destination of `Current result` was localhost, it was corrected.

**Comment by Reon90** [comment]
@cx20 fixed in 3.0.1

**Comment by cx20** [comment]
@Reon90 Thank you for the correction.
It is now displayed, but it seems to be a little different from the expected result.

Expected result:
https://github.com/vpenades/glTF-Sample-Models/tree/master/2.0/RecursiveSkeletons
![image](https://user-images.githubusercontent.com/1833979/117655177-b3567100-b1d1-11eb-9a3d-dd548fb897a2.png)

RedCube.js v3.0.1 result:
![image](https://user-images.githubusercontent.com/1833979/117654862-4ba02600-b1d1-11eb-80bf-21c01ec536d1.png)

**Comment by Reon90** [comment]
@cx20 fixed in 3.0.2. Please update rest failed tests.

**Comment by cx20** [comment]
@Reon90 Thanks for the fix. I have confirmed that the sample below passes the test.
- [MorphStressTest](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=MorphStressTest&scale=2.0&type=glTF)
- [RecursiveSkeletons](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=RecursiveSkeletons&scale=0.01&type=glTF)
- [TextureLinearInterpolationTest](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=TextureLinearInterpolationTest&scale=0.5&type=glTF)

**Comment by Reon90** [comment]
@cx20 thank you. Could you please also create a bug on the Environment Test?
