### ISSUE TITLE
RedCube does not support EXT_lights_image_based

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#43]
I tried to display the [EnvironmentTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/EnvironmentTest) from the [EXT_lights_image_based](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/EXT_lights_image_based) extension in RedCube.
However, the display result was different from Babylon.js. The main difference is whether CubeMap (Skybox) is applied or not.

|model|EnvironmentTest/glTF-IBL|
|:-----:|:-----:|
|Babylon.js|[![image](https://user-images.githubusercontent.com/1833979/120335536-80b11b80-c32c-11eb-977b-8f0da4f48340.png)](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=EnvironmentTest&scale=0.3&type=glTF-IBL)|
|RedCube|[![image](https://user-images.githubusercontent.com/1833979/120335558-87d82980-c32c-11eb-9ddc-5c94d37ea1e7.png)](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=EnvironmentTest&scale=0.3&type=glTF-IBL)|

Since the [EXT_lights_image_based](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/EXT_lights_image_based) extension has `IBL` and `Cubemap`, it is expected that it will be applied when it is displayed.
The following CubeMap seems to be contained in this model.
![image](https://user-images.githubusercontent.com/1833979/120335849-c7067a80-c32c-11eb-960a-387a0e45913a.png)

**Comment by Reon90** [comment]
fixed in 3.2.0

**Comment by Reon90** [comment]
@cx20 could you check?

**Comment by cx20** [comment]
Sorry for my late reply.
I have confirmed that the latest version of RedCube shows the CubeMap.

[![image](https://user-images.githubusercontent.com/1833979/163674253-7170fbe9-3722-46cf-97c8-745b23167bdf.png)](https://cx20.github.io/gltf-test/examples/redcube/index.html?category=tutorialModels&model=EnvironmentTest&scale=0.3&type=glTF-IBL)
