### ISSUE TITLE
double-sided of TextureSettingsTest.gltf does not pass

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#5]
I tried to display [TextureSettingsTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureSettingsTest) in RedCube.js.

However, double-sided of TextureSettingsTest.gltf does not pass.
[RedCube.js + TextureSettingTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/83ad9671670174a1d59ef33c2c7fadc3d036bd0f/examples/redcube/index.html?category=tutorialModels&model=TextureSettingsTest&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/50537656-ecb05800-0ba5-11e9-9ead-45e1b8815ed4.png)

Is this a problem when using PBR? The following is the display result when using your [sample](https://reon90.github.io/redcube/).
![image](https://user-images.githubusercontent.com/1833979/50537691-837d1480-0ba6-11e9-8b90-f125efb9226f.png)

![image](https://user-images.githubusercontent.com/1833979/50537696-9859a800-0ba6-11e9-85fa-f3135f52aaeb.png)

**Comment by cx20** [comment]
I changed env 1 to env 4, and confirmed that double-sided is displayed a little.
![image](https://user-images.githubusercontent.com/1833979/50537893-b5dc4100-0ba9-11e9-8599-e344c7f107ba.png)

Is this correct?

**Comment by Reon90** [comment]
@cx20 could you please merge https://github.com/cx20/gltf-test/pull/51

**Comment by cx20** [comment]
@Reon90 Thanks! I confirmed that this issue has been fixed in the latest RedCube.js.
[RedCube.js + TextureSettingsTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/0c351b089921c21f20b6493c5671ef3fd8aea3fa/examples/redcube/index.html?category=tutorialModels&model=TextureSettingsTest&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/50538937-7d456300-0bbb-11e9-8e71-f425b8ecf850.png)
