### ISSUE TITLE
Opaque of AlphaBlendModeTest.gltf has not passed

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#6]
I tried to display [AlphaBlendModeTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest) in RedCube.js.

However, Opaque of [AlphaBlendModeTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest) has not passed.
[RedCube.js + AlphaBlendModeTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/27f53fcbf46bfb38f9d801ca40338c90cbb7ad82/examples/redcube/index.html?category=tutorialModels&model=AlphaBlendModeTest&scale=0.5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/50539459-fe085d00-0bc3-11e9-8013-206d6f8d5c67.png)

[Three.js  + AlphaBlendModeTest.gltf resutl:](https://rawcdn.githack.com/cx20/gltf-test/27f53fcbf46bfb38f9d801ca40338c90cbb7ad82/examples/threejs/index.html?category=tutorialModels&model=AlphaBlendModeTest&scale=0.5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/50539486-65bea800-0bc4-11e9-9d46-a7008bbd21dc.png)

**Comment by cx20** [comment]
I confirmed that the problem of Opaque of AlphaBlendModeTest.gltf and BarramundiFish.gltf was solved in the latest version of RedCube.js.
[RedCube.js + AlphaBlendModeTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/a9cda755ff1c6656c5b3797b8747153e9e630947/examples/redcube/index.html?category=tutorialModels&model=AlphaBlendModeTest&scale=0.5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/50546008-fbf5db00-0c63-11e9-9e06-c49abf23e79c.png)

[RedCube.js + BarramundiFish.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/a9cda755ff1c6656c5b3797b8747153e9e630947/examples/redcube/index.html?category=tutorialModels&model=BarramundiFish&scale=5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/50546022-38c1d200-0c64-11e9-842f-01be484df83f.png)

**Comment by cx20** [comment]
@Reon90  tested [AlphaBlendModeTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest) again with RedCube.js v2.0.9.
However, it seems to be whiter than before.

[RedCube.js v2.0.9 + AlphaBlendModeTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/b0a3fbe21b98507e68954ed7a0bbf2cb8a4bc702/examples/redcube/index.html?category=tutorialModels&model=AlphaBlendModeTest&scale=0.5&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/50997845-0455ec00-1569-11e9-8f5b-09d55e2914ce.png)

Is it a problem of light? Or is there a problem with how to use the library?

**Comment by Reon90** [comment]
@cx20 it's a light intensity, I decrease it
