### ISSUE TITLE
Bear's model is not displayed in the correct orientation

### ISSUE THREAD

**Issue by cx20** [Reon90/redcube#8]
I tried to display the bear's model that was in sketchfab in RedCube.js.
https://sketchfab.com/models/f2f13a8630004b1c82730d8b9ffa0e1f

However, Bear's model is not displayed in the correct orientation

[RedCube.js + Bear model result:](http://jsdo.it/cx20/ELDw)
![image](https://user-images.githubusercontent.com/1833979/50548936-2c576c80-0c98-11e9-87e1-2c1b6a8c1133.png)

[Three.js + Bear model result:](http://jsdo.it/cx20/6MMO)
![image](https://user-images.githubusercontent.com/1833979/50548948-59a41a80-0c98-11e9-97a0-8f8d6242e856.png)

**Comment by Reon90** [comment]
Was fixed in 2.0.5

**Comment by cx20** [comment]
I confirmed that this issue has been fixed in the latest version.
[RedCube.js + Bear model result:](http://jsdo.it/cx20/KC3G)
![image](https://user-images.githubusercontent.com/1833979/50579676-99325880-0e8a-11e9-84f8-5fd54c933537.png)

**Comment by cx20** [comment]
@Reon90 BTW, where can I check version information?
I think that it is convenient when it is output to the console.
